import os
import re
import sys
import webbrowser
import snowflake.connector
import streamlit as st

DEFAULT_DATABASE = "PROD_GTED_HUB"
DEFAULT_SCHEMA = "CUR_CLIN_VEEVA_CTMS"
SNOWFLAKE_ACCOUNT = "colgatepalmoliveprod.us-central1.gcp"


class StreamlitOutputInterceptor:
    """Redirects stdout to capture console messages generated by snowflake-connector."""
    def __init__(self):
        self._stdout = sys.stdout
        self.output = []

    def write(self, text):
        self._stdout.write(text)
        if text.strip():
            self.output.append(text)

    def flush(self):
        self._stdout.flush()


@st.cache_resource(ttl=3600)
def get_snowflake_connection(
    user_id: str,
    database: str = DEFAULT_DATABASE,
    schema: str = DEFAULT_SCHEMA,
):
    """
    Universal cached Snowflake connection helper.
    - Local Desktop: Launches browser SSO pop-up automatically.
    - Streamlit Cloud / Headless: Captures and displays clickable SSO link in Streamlit UI.
    """
    print(f"⚡ [LakeStudio Auth] Initializing Snowflake session for {user_id}...")

    # 1. Use Streamlit Cloud Secrets if available (service account mode)
    if "snowflake" in st.secrets:
        conn = snowflake.connector.connect(
            user=st.secrets["snowflake"].get("user", user_id),
            password=st.secrets["snowflake"]["password"],
            account=st.secrets["snowflake"].get("account", SNOWFLAKE_ACCOUNT),
            warehouse=st.secrets["snowflake"].get("warehouse", "GTED_WH"),
            database=database,
            schema=schema,
        )
        return conn

    # 2. External Browser SSO Auth with console URL interception
    interceptor = StreamlitOutputInterceptor()
    original_stdout = sys.stdout
    sys.stdout = interceptor

    try:
        conn = snowflake.connector.connect(
            user=user_id,
            account=SNOWFLAKE_ACCOUNT,
            authenticator="externalbrowser",
            database=database,
            schema=schema,
        )
        return conn
    except Exception as err:
        sys.stdout = original_stdout
        captured_text = "".join(interceptor.output)

        # Extract SSO authorization URL if captured in stdout logs
        urls = re.findall(r"https://[^\s]+", captured_text)
        if urls:
            sso_url = urls[0]
            st.error("🔒 **Snowflake SSO Authentication Required**")
            st.markdown(
                f"Automatic browser pop-up is unavailable in this environment.\n\n"
                f"👉 **[Click Here to Authenticate with Colgate SSO]({sso_url})**"
            )
            st.caption(
                "Once authenticated in your browser tab, re-run the action or refresh the page."
            )
        else:
            st.error(f"❌ Snowflake Authentication Error: {str(err)}")
            
        raise ConnectionError(f"Snowflake SSO Authentication failed: {str(err)}")
    finally:
        sys.stdout = original_stdout
